class_name QuestIds

const BUY_INGREDIENTS := &"BUY_INGREDIENTS"
const MOVE_PRODUCTS := &"MOVE_PRODUCTS"
const MAKE_PIZZA := &"MAKE_PIZZA"
const PLACE_PIZZA := &"PLACE_PIZZA"
const BUY_TABLE := &"BUY_TABLE"
const CHANGE_STORE_NAME := &"CHANGE_STORE_NAME"
const OPEN_PIZZERIA := &"OPEN_PIZZERIA"
const SERVE_CUSTOMERS := &"SERVE_CUSTOMERS"
const CLOSE_PIZZERIA := &"CLOSE_PIZZERIA"
const FIND_DOUGH := &"FIND_DOUGH"
